version: '3.8'

services:
  backend:
    build: ./converter-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
